version: "3.9"

services:
  db:
    image: postgres
    env_file:
      - ./innotter/.env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 5s
      retries: 5

  innotter:
    build: innotter
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery
    env_file:
      - ./innotter/.env
    volumes:
      - ./innotter:/app/main

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - ./innotter/.env
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    build: innotter
    command: celery -A innotter worker -l info
    env_file:
      - ./innotter/.env
    volumes:
      - ./innotter:/app/main
    depends_on:
      - rabbitmq

  microservice:
    build:
      context: microservice
      dockerfile: Dockerfile
      target: main
    ports:
      - "8080:8080"
    volumes:
      - ./microservice:/app/microservice

  workers:
    build:
      context: microservice
      dockerfile: Dockerfile
      target: workers
    volumes:
      - ./microservice:/app/microservice
