version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=innotter_db
    expose:
      - "5432"

  innotter:
    build: innotter
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./innotter/.env
