# Generated by Django 4.1.2 on 2022-10-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_title_alter_page_follow_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
