# Generated by Django 4.1.3 on 2022-11-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
