# Generated by Django 4.1.2 on 2022-10-28 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_page_image'),
        ('user', '0002_user_liked_alter_user_refresh_token_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liked_by', to='posts.post'),
        ),
    ]
