# Generated by Django 4.1.2 on 2022-10-28 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_page_image'),
        ('user', '0003_alter_user_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disliked_by', to='posts.post'),
        ),
    ]
