# Generated by Django 4.1.2 on 2022-10-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_page_image'),
        ('user', '0004_user_disliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='disliked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='liked',
        ),
        migrations.AddField(
            model_name='user',
            name='disliked',
            field=models.ManyToManyField(blank=True, null=True, related_name='disliked_by', to='posts.post'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_by', to='posts.post'),
        ),
    ]
