# Generated by Django 4.1.2 on 2022-10-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_disliked_remove_user_liked_user_disliked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='disliked',
        ),
    ]
