# Generated by Django 4.1.2 on 2022-10-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_liked_alter_user_refresh_token_alter_user_role'),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
